---
- hosts: webserver
  tasks: 
    - name: Install nginx webserver
      apt: name=apache2 state=present
    - name: copy index html file
      copy: src=index.ht dest=/var/www/html
      notify: restart the service
  handlers: 
    - name: restart the service
      service: name=apache2 state=started
