---
- hosts: webserver
  gather_facts: no
  tasks: 
    - name: Install nginx webserver
      apt: name=apache2 state=present
      when: ansible_pkg_mgr == "apt"
      tags:
        - package
    - name: copy index html file
      copy: src=index.html dest=/var/www/html
      tags:
        - copy
    - name: start the service
      service: name=apache2 state=started
